name: teleport-tbot
version: 0.4.0
description: "Teleport TBOT"
home: "https://github.com/giantswarm/teleport-tbot"
apiVersion: v1
annotations:
  application.giantswarm.io/team: "shield"
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "true"
icon: https://s.giantswarm.io/app-icons/teleport/1/light.png
maintainers:
  - name: giantswarm/team-shield
    email: team-shield@giantswarm.io
keywords:
  - teleport
